---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[skype-app]
    attributes:
  - name: uninstall
    run_list:
      - recipe[skype-app_test::uninstall]
    attributes:
